### ISSUE TITLE
Error coming when using Style 15

### ISSUE THREAD

**Issue by romaan-khan** [jb3rndt/PersistentBottomNavBarV2#51]
======== Exception caught by rendering library =====================================================
The following assertion was thrown during paint():
RenderBox was not laid out: RenderCustomPaint#7ebba relayoutBoundary=up9
'package:flutter/src/rendering/box.dart':
Failed assertion: line 1979 pos 12: 'hasSize'

Either the assertion indicates an error in the framework itself, or we should provide substantially more information in this error message to help you determine and fix the underlying cause.
In either case, please report this assertion by filing a bug on GitHub:
  https://github.com/flutter/flutter/issues/new?template=2_bug.md

```
The relevant error-causing widget was: 
  PersistentTabView PersistentTabView:file:///D:/work/medbuddi/lib/ui/base_view/base_view.dart:24:16
When the exception was thrown, this was the stack: 
#2      RenderBox.size (package:flutter/src/rendering/box.dart:1979:12)
#3      RenderCustomPaint._paintWithPainter (package:flutter/src/rendering/custom_paint.dart:563:27)
#4      RenderCustomPaint.paint (package:flutter/src/rendering/custom_paint.dart:610:7)
#5      RenderObject._paintWithContext (package:flutter/src/rendering/object.dart:2477:7)
#6      PaintingContext.paintChild (package:flutter/src/rendering/object.dart:187:13)
#7      RenderClipPath.paint (package:flutter/src/rendering/proxy_box.dart:1725:17)
#8      RenderObject._paintWithContext (package:flutter/src/rendering/object.dart:2477:7)
#9      PaintingContext.paintChild (package:flutter/src/rendering/object.dart:187:13)
#10     RenderShiftedBox.paint (package:flutter/src/rendering/shifted_box.dart:79:15)
#11     RenderObject._paintWithContext (package:flutter/src/rendering/object.dart:2477:7)
#12     PaintingContext.paintChild (package:flutter/src/rendering/object.dart:187:13)
#13     RenderShiftedBox.paint (package:flutter/src/rendering/shifted_box.dart:79:15)
#14     RenderObject._paintWithContext (package:flutter/src/rendering/object.dart:2477:7)
#15     PaintingContext.paintChild (package:flutter/src/rendering/object.dart:187:13)
#16     RenderBoxContainerDefaultsMixin.defaultPaint (package:flutter/src/rendering/box.dart:2844:15)
#17     RenderStack.paintStack (package:flutter/src/rendering/stack.dart:611:5)
#18     RenderStack.paint (package:flutter/src/rendering/stack.dart:627:7)
#19     RenderObject._paintWithContext (package:flutter/src/rendering/object.dart:2477:7)
#20     PaintingContext.paintChild (package:flutter/src/rendering/object.dart:187:13)
#21     RenderShiftedBox.paint (package:flutter/src/rendering/shifted_box.dart:79:15)
#22     RenderObject._paintWithContext (package:flutter/src/rendering/object.dart:2477:7)
#23     PaintingContext.paintChild (package:flutter/src/rendering/object.dart:187:13)
#24     RenderProxyBoxMixin.paint (package:flutter/src/rendering/proxy_box.dart:140:15)
#25     RenderObject._paintWithContext (package:flutter/src/rendering/object.dart:2477:7)
#26     PaintingContext.paintChild (package:flutter/src/rendering/object.dart:187:13)
#27     RenderProxyBoxMixin.paint (package:flutter/src/rendering/proxy_box.dart:140:15)
#28     RenderObject._paintWithContext (package:flutter/src/rendering/object.dart:2477:7)
#29     PaintingContext.paintChild (package:flutter/src/rendering/object.dart:187:13)
#30     RenderShiftedBox.paint (package:flutter/src/rendering/shifted_box.dart:79:15)
#31     RenderObject._paintWithContext (package:flutter/src/rendering/object.dart:2477:7)
#32     PaintingContext.paintChild (package:flutter/src/rendering/object.dart:187:13)
#33     RenderBoxContainerDefaultsMixin.defaultPaint (package:flutter/src/rendering/box.dart:2844:15)
#34     RenderStack.paintStack (package:flutter/src/rendering/stack.dart:611:5)
#35     RenderStack.paint (package:flutter/src/rendering/stack.dart:627:7)
#36     RenderObject._paintWithContext (package:flutter/src/rendering/object.dart:2477:7)
#37     PaintingContext.paintChild (package:flutter/src/rendering/object.dart:187:13)
#38     RenderProxyBoxMixin.paint (package:flutter/src/rendering/proxy_box.dart:140:15)
#39     RenderObject._paintWithContext (package:flutter/src/rendering/object.dart:2477:7)
#40     PaintingContext.paintChild (package:flutter/src/rendering/object.dart:187:13)
#41     RenderShiftedBox.paint (package:flutter/src/rendering/shifted_box.dart:79:15)
#42     RenderObject._paintWithContext (package:flutter/src/rendering/object.dart:2477:7)
#43     PaintingContext.paintChild (package:flutter/src/rendering/object.dart:187:13)
#44     RenderProxyBoxMixin.paint (package:flutter/src/rendering/proxy_box.dart:140:15)
#45     RenderDecoratedBox.paint (package:flutter/src/rendering/proxy_box.dart:2191:11)
#46     RenderObject._paintWithContext (package:flutter/src/rendering/object.dart:2477:7)
#47     PaintingContext.paintChild (package:flutter/src/rendering/object.dart:187:13)
#48     RenderShiftedBox.paint (package:flutter/src/rendering/shifted_box.dart:79:15)
#49     RenderObject._paintWithContext (package:flutter/src/rendering/object.dart:2477:7)
#50     PaintingContext.paintChild (package:flutter/src/rendering/object.dart:187:13)
#51     RenderProxyBoxMixin.paint (package:flutter/src/rendering/proxy_box.dart:140:15)
#52     RenderTransform.paint (package:flutter/src/rendering/proxy_box.dart:2419:17)
#53     RenderObject._paintWithContext (package:flutter/src/rendering/object.dart:2477:7)
#54     PaintingContext.paintChild (package:flutter/src/rendering/object.dart:187:13)
#55     RenderShiftedBox.paint (package:flutter/src/rendering/shifted_box.dart:79:15)
#56     RenderObject._paintWithContext (package:flutter/src/rendering/object.dart:2477:7)
#57     PaintingContext.paintChild (package:flutter/src/rendering/object.dart:187:13)
#58     RenderBoxContainerDefaultsMixin.defaultPaint (package:flutter/src/rendering/box.dart:2844:15)
#59     RenderStack.paintStack (package:flutter/src/rendering/stack.dart:611:5)
#60     RenderStack.paint (package:flutter/src/rendering/stack.dart:627:7)
#61     RenderObject._paintWithContext (package:flutter/src/rendering/object.dart:2477:7)
#62     PaintingContext.paintChild (package:flutter/src/rendering/object.dart:187:13)
#63     RenderProxyBoxMixin.paint (package:flutter/src/rendering/proxy_box.dart:140:15)
#64     RenderDecoratedBox.paint (package:flutter/src/rendering/proxy_box.dart:2191:11)
#65     RenderObject._paintWithContext (package:flutter/src/rendering/object.dart:2477:7)
#66     PaintingContext.paintChild (package:flutter/src/rendering/object.dart:187:13)
#67     RenderShiftedBox.paint (package:flutter/src/rendering/shifted_box.dart:79:15)
#68     RenderObject._paintWithContext (package:flutter/src/rendering/object.dart:2477:7)
#69     PaintingContext.paintChild (package:flutter/src/rendering/object.dart:187:13)
#70     RenderBoxContainerDefaultsMixin.defaultPaint (package:flutter/src/rendering/box.dart:2844:15)
#71     RenderStack.paintStack (package:flutter/src/rendering/stack.dart:611:5)
#72     RenderStack.paint (package:flutter/src/rendering/stack.dart:627:7)
#73     RenderObject._paintWithContext (package:flutter/src/rendering/object.dart:2477:7)
#74     PaintingContext.paintChild (package:flutter/src/rendering/object.dart:187:13)
#75     RenderProxyBoxMixin.paint (package:flutter/src/rendering/proxy_box.dart:140:15)
#76     RenderDecoratedBox.paint (package:flutter/src/rendering/proxy_box.dart:2191:11)
#77     RenderObject._paintWithContext (package:flutter/src/rendering/object.dart:2477:7)
#78     PaintingContext.paintChild (package:flutter/src/rendering/object.dart:187:13)
#79     RenderProxyBoxMixin.paint (package:flutter/src/rendering/proxy_box.dart:140:15)
#80     RenderObject._paintWithContext (package:flutter/src/rendering/object.dart:2477:7)
#81     PaintingContext.paintChild (package:flutter/src/rendering/object.dart:187:13)
#82     RenderBoxContainerDefaultsMixin.defaultPaint (package:flutter/src/rendering/box.dart:2844:15)
#83     RenderCustomMultiChildLayoutBox.paint (package:flutter/src/rendering/custom_layout.dart:408:5)
#84     RenderObject._paintWithContext (package:flutter/src/rendering/object.dart:2477:7)
#85     PaintingContext.paintChild (package:flutter/src/rendering/object.dart:187:13)
#86     RenderProxyBoxMixin.paint (package:flutter/src/rendering/proxy_box.dart:140:15)
#87     _RenderInkFeatures.paint (package:flutter/src/material/material.dart:604:11)
#88     RenderObject._paintWithContext (package:flutter/src/rendering/object.dart:2477:7)
#89     PaintingContext.paintChild (package:flutter/src/rendering/object.dart:187:13)
#90     RenderProxyBoxMixin.paint (package:flutter/src/rendering/proxy_box.dart:140:15)
#91     PaintingContext.pushLayer (package:flutter/src/rendering/object.dart:387:12)
#92     RenderPhysicalModel.paint (package:flutter/src/rendering/proxy_box.dart:1951:15)
#93     RenderObject._paintWithContext (package:flutter/src/rendering/object.dart:2477:7)
#94     PaintingContext.paintChild (package:flutter/src/rendering/object.dart:187:13)
#95     RenderProxyBoxMixin.paint (package:flutter/src/rendering/proxy_box.dart:140:15)
#96     RenderObject._paintWithContext (package:flutter/src/rendering/object.dart:2477:7)
#97     PaintingContext.paintChild (package:flutter/src/rendering/object.dart:187:13)
#98     RenderProxyBoxMixin.paint (package:flutter/src/rendering/proxy_box.dart:140:15)
#99     RenderObject._paintWithContext (package:flutter/src/rendering/object.dart:2477:7)
#100    PaintingContext._repaintCompositedChild (package:flutter/src/rendering/object.dart:141:11)
#101    PaintingContext.repaintCompositedChild (package:flutter/src/rendering/object.dart:100:5)
#102    PaintingContext._compositeChild (package:flutter/src/rendering/object.dart:198:7)
#103    PaintingContext.paintChild (package:flutter/src/rendering/object.dart:185:7)
#104    RenderProxyBoxMixin.paint (package:flutter/src/rendering/proxy_box.dart:140:15)
#105    RenderObject._paintWithContext (package:flutter/src/rendering/object.dart:2477:7)
#106    PaintingContext.paintChild (package:flutter/src/rendering/object.dart:187:13)
#107    RenderProxyBoxMixin.paint (package:flutter/src/rendering/proxy_box.dart:140:15)
#108    RenderTransform.paint (package:flutter/src/rendering/proxy_box.dart:2419:17)
#109    RenderObject._paintWithContext (package:flutter/src/rendering/object.dart:2477:7)
#110    PaintingContext.paintChild (package:flutter/src/rendering/object.dart:187:13)
#111    RenderProxyBoxMixin.paint (package:flutter/src/rendering/proxy_box.dart:140:15)
#112    PaintingContext.pushLayer (package:flutter/src/rendering/object.dart:387:12)
#113    PaintingContext.pushOpacity (package:flutter/src/rendering/object.dart:608:5)
#114    RenderAnimatedOpacityMixin.paint (package:flutter/src/rendering/proxy_box.dart:1008:23)
#115    RenderObject._paintWithContext (package:flutter/src/rendering/object.dart:2477:7)
#116    PaintingContext.paintChild (package:flutter/src/rendering/object.dart:187:13)
#117    RenderProxyBoxMixin.paint (package:flutter/src/rendering/proxy_box.dart:140:15)
#118    RenderTransform.paint (package:flutter/src/rendering/proxy_box.dart:2419:17)
#119    RenderObject._paintWithContext (package:flutter/src/rendering/object.dart:2477:7)
#120    PaintingContext.paintChild (package:flutter/src/rendering/object.dart:187:13)
#121    RenderProxyBoxMixin.paint (package:flutter/src/rendering/proxy_box.dart:140:15)
#122    PaintingContext.pushLayer (package:flutter/src/rendering/object.dart:387:12)
#123    PaintingContext.pushOpacity (package:flutter/src/rendering/object.dart:608:5)
#124    RenderAnimatedOpacityMixin.paint (package:flutter/src/rendering/proxy_box.dart:1008:23)
#125    RenderObject._paintWithContext (package:flutter/src/rendering/object.dart:2477:7)
#126    PaintingContext.paintChild (package:flutter/src/rendering/object.dart:187:13)
#127    _RenderColoredBox.paint (package:flutter/src/widgets/basic.dart:7510:15)
#128    RenderObject._paintWithContext (package:flutter/src/rendering/object.dart:2477:7)
#129    PaintingContext.paintChild (package:flutter/src/rendering/object.dart:187:13)
#130    RenderProxyBoxMixin.paint (package:flutter/src/rendering/proxy_box.dart:140:15)
#131    RenderTransform.paint (package:flutter/src/rendering/proxy_box.dart:2419:17)
#132    RenderObject._paintWithContext (package:flutter/src/rendering/object.dart:2477:7)
#133    PaintingContext.paintChild (package:flutter/src/rendering/object.dart:187:13)
#134    RenderProxyBoxMixin.paint (package:flutter/src/rendering/proxy_box.dart:140:15)
#135    PaintingContext.pushLayer (package:flutter/src/rendering/object.dart:387:12)
#136    PaintingContext.pushOpacity (package:flutter/src/rendering/object.dart:608:5)
#137    RenderAnimatedOpacityMixin.paint (package:flutter/src/rendering/proxy_box.dart:1008:23)
#138    RenderObject._paintWithContext (package:flutter/src/rendering/object.dart:2477:7)
#139    PaintingContext.paintChild (package:flutter/src/rendering/object.dart:187:13)
#140    RenderProxyBoxMixin.paint (package:flutter/src/rendering/proxy_box.dart:140:15)
#141    RenderTransform.paint (package:flutter/src/rendering/proxy_box.dart:2419:17)
#142    RenderObject._paintWithContext (package:flutter/src/rendering/object.dart:2477:7)
#143    PaintingContext.paintChild (package:flutter/src/rendering/object.dart:187:13)
#144    RenderProxyBoxMixin.paint (package:flutter/src/rendering/proxy_box.dart:140:15)
#145    PaintingContext.pushLayer (package:flutter/src/rendering/object.dart:387:12)
#146    PaintingContext.pushOpacity (package:flutter/src/rendering/object.dart:608:5)
#147    RenderAnimatedOpacityMixin.paint (package:flutter/src/rendering/proxy_box.dart:1008:23)
#148    RenderObject._paintWithContext (package:flutter/src/rendering/object.dart:2477:7)
#149    PaintingContext.paintChild (package:flutter/src/rendering/object.dart:187:13)
#150    _RenderColoredBox.paint (package:flutter/src/widgets/basic.dart:7510:15)
#151    RenderObject._paintWithContext (package:flutter/src/rendering/object.dart:2477:7)
#152    PaintingContext.paintChild (package:flutter/src/rendering/object.dart:187:13)
#153    RenderProxyBoxMixin.paint (package:flutter/src/rendering/proxy_box.dart:140:15)
#154    RenderObject._paintWithContext (package:flutter/src/rendering/object.dart:2477:7)
#155    PaintingContext._repaintCompositedChild (package:flutter/src/rendering/object.dart:141:11)
#156    PaintingContext.repaintCompositedChild (package:flutter/src/rendering/object.dart:100:5)
#157    PaintingContext._compositeChild (package:flutter/src/rendering/object.dart:198:7)
#158    PaintingContext.paintChild (package:flutter/src/rendering/object.dart:185:7)
#159    RenderProxyBoxMixin.paint (package:flutter/src/rendering/proxy_box.dart:140:15)
#160    RenderObject._paintWithContext (package:flutter/src/rendering/object.dart:2477:7)
#161    PaintingContext.paintChild (package:flutter/src/rendering/object.dart:187:13)
#162    RenderProxyBoxMixin.paint (package:flutter/src/rendering/proxy_box.dart:140:15)
#163    RenderObject._paintWithContext (package:flutter/src/rendering/object.dart:2477:7)
#164    PaintingContext.paintChild (package:flutter/src/rendering/object.dart:187:13)
#165    RenderProxyBoxMixin.paint (package:flutter/src/rendering/proxy_box.dart:140:15)
#166    RenderOffstage.paint (package:flutter/src/rendering/proxy_box.dart:3475:11)
#167    RenderObject._paintWithContext (package:flutter/src/rendering/object.dart:2477:7)
#168    PaintingContext.paintChild (package:flutter/src/rendering/object.dart:187:13)
#169    RenderProxyBoxMixin.paint (package:flutter/src/rendering/proxy_box.dart:140:15)
#170    RenderObject._paintWithContext (package:flutter/src/rendering/object.dart:2477:7)
#171    PaintingContext.paintChild (package:flutter/src/rendering/object.dart:187:13)
#172    _RenderTheatre.paintStack (package:flutter/src/widgets/overlay.dart:786:15)
#173    _RenderTheatre.paint (package:flutter/src/widgets/overlay.dart:804:7)
#174    RenderObject._paintWithContext (package:flutter/src/rendering/object.dart:2477:7)
#175    PaintingContext.paintChild (package:flutter/src/rendering/object.dart:187:13)
#176    RenderProxyBoxMixin.paint (package:flutter/src/rendering/proxy_box.dart:140:15)
#177    RenderObject._paintWithContext (package:flutter/src/rendering/object.dart:2477:7)
#178    PaintingContext.paintChild (package:flutter/src/rendering/object.dart:187:13)
#179    RenderProxyBoxMixin.paint (package:flutter/src/rendering/proxy_box.dart:140:15)
#180    RenderObject._paintWithContext (package:flutter/src/rendering/object.dart:2477:7)
#181    PaintingContext.paintChild (package:flutter/src/rendering/object.dart:187:13)
#182    RenderProxyBoxMixin.paint (package:flutter/src/rendering/proxy_box.dart:140:15)
#183    RenderObject._paintWithContext (package:flutter/src/rendering/object.dart:2477:7)
#184    PaintingContext.paintChild (package:flutter/src/rendering/object.dart:187:13)
#185    RenderProxyBoxMixin.paint (package:flutter/src/rendering/proxy_box.dart:140:15)
#186    RenderObject._paintWithContext (package:flutter/src/rendering/object.dart:2477:7)
#187    PaintingContext.paintChild (package:flutter/src/rendering/object.dart:187:13)
#188    RenderProxyBoxMixin.paint (package:flutter/src/rendering/proxy_box.dart:140:15)
#189    RenderObject._paintWithContext (package:flutter/src/rendering/object.dart:2477:7)
#190    PaintingContext.paintChild (package:flutter/src/rendering/object.dart:187:13)
#191    RenderProxyBoxMixin.paint (package:flutter/src/rendering/proxy_box.dart:140:15)
#192    RenderObject._paintWithContext (package:flutter/src/rendering/object.dart:2477:7)
#193    PaintingContext.paintChild (package:flutter/src/rendering/object.dart:187:13)
#194    RenderProxyBoxMixin.paint (package:flutter/src/rendering/proxy_box.dart:140:15)
#195    RenderObject._paintWithContext (package:flutter/src/rendering/object.dart:2477:7)
#196    PaintingContext.paintChild (package:flutter/src/rendering/object.dart:187:13)
#197    _RenderLayoutBuilder.paint (package:flutter/src/widgets/layout_builder.dart:340:15)
#198    RenderObject._paintWithContext (package:flutter/src/rendering/object.dart:2477:7)
#199    PaintingContext.paintChild (package:flutter/src/rendering/object.dart:187:13)
#200    _RenderLayoutBuilder.paint (package:flutter/src/widgets/layout_builder.dart:340:15)
#201    RenderObject._paintWithContext (package:flutter/src/rendering/object.dart:2477:7)
#202    PaintingContext.paintChild (package:flutter/src/rendering/object.dart:187:13)
#203    RenderView.paint (package:flutter/src/rendering/view.dart:209:15)
#204    RenderObject._paintWithContext (package:flutter/src/rendering/object.dart:2477:7)
#205    PaintingContext._repaintCompositedChild (package:flutter/src/rendering/object.dart:141:11)
#206    PaintingContext.repaintCompositedChild (package:flutter/src/rendering/object.dart:100:5)
#207    PipelineOwner.flushPaint (package:flutter/src/rendering/object.dart:995:29)
#208    RendererBinding.drawFrame (package:flutter/src/rendering/binding.dart:506:19)
#209    WidgetsBinding.drawFrame (package:flutter/src/widgets/binding.dart:892:13)
#210    RendererBinding._handlePersistentFrameCallback (package:flutter/src/rendering/binding.dart:370:5)
#211    SchedulerBinding._invokeFrameCallback (package:flutter/src/scheduler/binding.dart:1146:15)
#212    SchedulerBinding.handleDrawFrame (package:flutter/src/scheduler/binding.dart:1083:9)
#213    SchedulerBinding._handleDrawFrame (package:flutter/src/scheduler/binding.dart:997:5)
#217    _invoke (dart:ui/hooks.dart:151:10)
#218    PlatformDispatcher._drawFrame (dart:ui/platform_dispatcher.dart:308:5)
#219    _drawFrame (dart:ui/hooks.dart:115:31)
(elided 5 frames from class _AssertionError and dart:async)
The following RenderObject was being processed when the exception was fired: RenderCustomPaint#7ebba relayoutBoundary=up9
...  parentData: <none> (can use size)
...  constraints: BoxConstraints(0.0<=w<=423.5, 0.0<=h<=51.0)
...  size: MISSING
...  painter: null
...  foregroundPainter: _ShapeBorderPainter#b8e93()
RenderObject: RenderCustomPaint#7ebba relayoutBoundary=up9
  parentData: <none> (can use size)
  constraints: BoxConstraints(0.0<=w<=423.5, 0.0<=h<=51.0)
  size: MISSING
  painter: null
  foregroundPainter: _ShapeBorderPainter#b8e93()
...  child: _RenderInkFeatures#82cc0 relayoutBoundary=up10
...    parentData: <none> (can use size)
...    constraints: BoxConstraints(0.0<=w<=423.5, 0.0<=h<=51.0)
...    size: MISSING
...    child: RenderFittedBox#819f3 relayoutBoundary=up11
...      parentData: <none> (can use size)
...      constraints: BoxConstraints(0.0<=w<=423.5, 0.0<=h<=51.0)
...      size: MISSING
...      fit: contain
...      alignment: Alignment.center
...      textDirection: ltr
...      child: RenderParagraph#569c3 relayoutBoundary=up12 NEEDS-PAINT
...        parentData: <none> (can use size)
...        constraints: BoxConstraints(unconstrained)
...        size: Size(0.0, 16.0)
...        textAlign: start
...        textDirection: ltr
...        softWrap: wrapping at box width
...        overflow: clip
...        locale: en_US
...        maxLines: unlimited
...        text: TextSpan
...          debugLabel: ((englishLike bodyMedium 2014).merge((blackMountainView bodyMedium).apply)).merge(unknown)
...          inherit: false
...          color: Color(0xff3aa2dc)
...          family: RedHatDisplay
...          size: 12.0
...          weight: 400
...          baseline: alphabetic
...          decoration: TextDecoration.none
...          ""
====================================================================================================
```

**Comment by jb3rndt** [comment]
I cant reproduce the issue. Can you give a reproducible example or find out which widget is throwing the error? It seems to be related to a `CustomPaint`, of which none are used in the package afaik.
